on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: True

jobs:
  feature-test:
    name: "Feature Test"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/feature-test@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  feature-test-namespaced:
    name: "Feature Test - Namespaced"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/feature-test-namespaced@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
