on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
    secrets:
      dev-hub-auth-url:
        required: true

jobs:
  feature-test:
    name: "Feature Test"
    description: "Create an unmanaged scratch org and run Apex tests using 'ci_feature'"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/feature-test@v1
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
  build-unlocked-test-package:
    name: "Build Unlocked Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/build-unlocked-test-package@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
  feature-test-2gp:
    name: "Feature Test - 2GP"
    runs-on: ubuntu-latest
    needs:
      - build-unlocked-test-package
    steps:
      - uses: cumulus-actions/feature-test-2gp@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
