on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: True

jobs:
  feature-test:
    name: "Feature Test"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/feature-test@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  feature-test-robot:
    name: "Feature Test - Robot"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/feature-test-robot@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  build-feature-test-package:
    name: "Build Feature Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/build-feature-test-package@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  feature-test-2gp:
    name: "Feature Test - 2GP"
    runs-on: ubuntu-latest
    needs:
      - build-feature-test-package
    steps:
      - uses: cumulusci-actions/feature-test-2gp@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  feature-test-robot-2gp:
    name: "Feature Test - Robot 2GP"
    runs-on: ubuntu-latest
    needs:
      - build-feature-test-package
    steps:
      - uses: cumulusci-actions/feature-test-robot-2gp@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
