on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
    secrets:
      dev-hub-auth-url:
        required: true

jobs:
  feature-test:
    name: "Feature Test"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/feature-test@v1
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
 
  build-unlocked-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Build Unlocked Test Package
        run: |
          cci flow run build_feature_test_package --org feature | tee /tmp/build.log
          echo "::set-output name=package_id::$(grep -P "04t.{15}" -o /tmp/build.log)"
          rm /tmp/build.log
  
  update-commit-status:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Sibz/github-status-action@v1
        name: Update Commit Status
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          description: 'version_id: ${{ steps.build_feature_test_package.outputs.package_id }}'
          state: 'success'
          sha: ${{ github.sha }}
  
  feature-test-2gp:
    name: "Feature Test - 2GP"
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs:
      - build-unlocked-test-package
    steps:
      - uses: cumulus-actions/feature-test-2gp@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
