on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: True

jobs:
  feature-test:
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/feature-test@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
  feature-test-namespaced:
    runs-on: ubuntu-latest
    steps:
      - uses: cumulusci-actions/feature-test-namespaced@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
